name: TheWalls
author: rubik_cube_man
main: rubik_cube_man.plugins.walls.Walls
softdepend: [Multiverse-Core, Multiworld, DimensionDoor]
version: 1.1.0.1
depend: [TagAPI]
softdepend: [Multiverse-Core, Multiworld, DimensionDoor]
load: POSTWORLD
commands:
  walls:
    usage: /<command>
    description: The Main Walls Command!
permissions:
  walls.create:
    description: Allows you to create and edit arenas
    default: op
  walls.delete:
    description: Allows you to delete unwanted arenas
    default: op
  walls.start:
    description: Allows you to force start an arena
    default: op
  walls.join:
    description: Allows you to join and use arenas
    default: true
  walls.signjoin:
    description: Allows you to join by clicking a sign
    default: true
  walls.leave:
    description: Allows you to leave walls arenas
    default: true
  walls.info:
    description: Allows you to see the infomation about an arena
    default: op